FROM zachgray/swift-tensorflow:4.2

MAINTAINER Zach Gray (zgray@scal.io)
LABEL maintainer="Zach Gray <zgray@scal.io>"
LABEL Description="Dockerized Swift for TensorFlow REPL"

CMD swift -I/usr/lib/swift/clang/include